#pragma once

#define MESSAGE_PROTOCOL Default_Protocol

#define SERVER_IP INADDR_ANY
#define SERVER_PORT 53132
#define SERVER_PENDING_CONNECTION_QUEUE_SIZE 100
#define SERVER_PROTOCOL_FAMILY AF_INET